repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: local
    hooks:
      - id: otel-unit-tests
        name: otel unit tests
        entry: bash scripts/test
        language: system
        pass_filenames: false
