services:
  otel-collector:
    image: otel/opentelemetry-collector:0.148.0
    restart: unless-stopped
    command:
      - --config=/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol/config.yaml:ro
    depends_on:
      - lgtm

  lgtm:
    image: grafana/otel-lgtm:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./.data/lgtm:/data
